INSERT INTO tipo_base(tipo, nombre, descripcion)
VALUES
	('TIPO_BIEN', 'Bolsas de plástico diseñadas para llevar o cargar bienes por los consumidores o usuarios', 'Bolsas de plástico diseñadas para llevar o cargar bienes por los consumidores o usuarios'),
    ('TIPO_BIEN', 'Bolsas para alimentos a granel', 'Bolsas para alimentos a granel'),
    ('TIPO_BIEN', 'Bolsas para alimentos de origen animal', 'Bolsas para alimentos de origen animal'),
    ('TIPO_BIEN', 'Bolsas para limpieza (basura)', 'Bolsas para limpieza (basura)'),
    ('TIPO_BIEN', 'Sorbetes de plástico (pajitas, pitillos, popotes, cañitas, otras demoninaciones similares)', 'Sorbetes de plástico (pajitas, pitillos, popotes, cañitas, otras demoninaciones similares)'),
    ('TIPO_BIEN', 'Recipientes, envases para alimentos de consumo humano', 'Recipientes, envases para alimentos de consumo humano'),
    ('TIPO_BIEN', 'Envases, vasos para bebidas de consumo humano', 'Envases, vasos para bebidas de consumo humano'),
    ('TIPO_BIEN', 'Vajilla y otros utensilios de mesa', 'Vajilla y otros utensilios de mesa'),
    ('TIPO_BIEN', 'Botellas de plástico', 'Botellas de plástico'),
    ('TIPO_BIEN', 'Insumos para la elaboración de botellas', 'Insumos para la elaboración de botellas'),
    ('TIPO_BIEN', 'Bolsa multimaterial de plástico y papel', 'Bolsa multimaterial de plástico y papel'),
    ('TIPO_BIEN', 'Bolsa multimaterial de plástico y aluminio', 'Bolsa multimaterial de plástico y aluminio'),
    ('TIPO_BIEN', 'Otros bienes de base polimérica', 'Otros bienes de base polimérica'),
    ('TIPO_RESINA', 'PET', 'PET'),
    ('TIPO_RESINA', 'HDPE/PEAD', 'HDPE/PEAD'),
    ('TIPO_RESINA', 'PVC', 'PVC'),
    ('TIPO_RESINA', 'LDPE/PEBD', 'LDPE/PEBD'),
    ('TIPO_RESINA', 'PP (Polipropileno)', 'PP (Polipropileno)'),
    ('TIPO_RESINA', 'PS (Poliestireno)', 'PS (Poliestireno)'),
    ('TIPO_RESINA', 'EPS (Poliestireno expandido)', 'EPS (Poliestireno expandido)'),
    ('TIPO_RESINA', 'EPX (Poliestireno extruído)', 'EPX (Poliestireno extruído)'),
    ('TIPO_RESINA', 'PLA', 'PLA'),
    ('TIPO_RESINA', 'Otros', 'Otros'),
    ('TIPO_USO', 'Un Solo Uso', 'Un Solo Uso'),
    ('TIPO_USO', 'Reutilizable Retornable', 'Reutilizable Retornable'),
    ('TIPO_USO', 'Reutilizable No Retornable', 'Reutilizable No Retornable'),
    ('FORMA_VALORIZACION', 'Reciclable', 'Reciclable'),
    ('FORMA_VALORIZACION', 'Compostable', 'Compostable'),
    ('FORMA_VALORIZACION', 'Otro', 'Otro'),
    ('FORMA_VALORIZACION', 'Ninguna', 'Ninguna'),
    ('TIPO_DECLARACION', 'Fabricación', 'Fabricación'),
    ('TIPO_DECLARACION', 'Importación', 'Importación'),
    ('TIPO_DECLARACION', 'Adquisición', 'Adquisición'),
    ('TIPO_DECLARACION', 'Distribución', 'Distribución');