CREATE TABLE role(
	id_role BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    role_name VARCHAR(20),
    PRIMARY KEY (id_role)
    )ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;