CREATE TABLE tipo_base(
	id_tipo_base BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	tipo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(300) NOT NULL,
	PRIMARY KEY (id_tipo_base)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;