CREATE TABLE empresa(
	id_empresa BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ruc VARCHAR(15) NOT NULL,
    razon_social VARCHAR(300) NOT NULL,
	PRIMARY KEY (id_empresa)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;