CREATE TABLE proveedor(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ruc VARCHAR(15) NOT NULL,
    nombre VARCHAR(300) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;